# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Release
on:
  release:
    types:
      - released

env:
  ARTIFACTS_API_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  ARTIFACTS_FEED_URL: ${{ secrets.AZURE_ARTIFACTS_FEED_URL }}
  ARTIFACTS_PACKAGES_URL: ${{ secrets.ARTIFACTS_PACKAGES_URL }}
  ARTIFACTS_USERNAME: ${{ secrets.AZURE_ARTIFACTS_USER_NAME }}

jobs:
  delete-pre-releases:
    name: Delete Unnecessary Pre-Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0

      - name: Delete other pre-releases and their tags
        shell: pwsh
        run: |
          $release = "${{ github.ref_name }}"
          $repo = "${{ github.repository }}"
          $token = "${{ secrets.GITHUB_TOKEN }}"

          # example: "AdminApp.Web-v2.5.1"
          # output: "AdminApp.Web"
          $packageName = ($release -split "-v")[0]

          $page = 1
          $release_list = @()

          Do {

            $url = "https://api.github.com/repos/$repo/releases?per_page=100&page=$page"
            $gh_headers = @{
                "Accept"        = "application/vnd.github+json"
                "Authorization" = "Bearer $token"
            }

            $release_list = Invoke-RestMethod $url -Headers $gh_headers

            $release_list | ForEach-Object {
                if ($_.tag_name -like "$($packageName)-*" -and $_.prerelease) {
                    "Deleting pre-release $($_.tag_name)" | Write-Output
                    Invoke-RestMethod -Method Delete -Uri $_.url -Headers $gh_headers
                }
            }

            $page += 1
          } While ($release_list.count -gt 0)

  promote-Azure-artifact:
    name: Promote Azure Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0

      - name: Promote Package
        if: "! github.event.pull_request.head.repo.fork"
        run: |
          $release = "${{ github.ref_name }}"

          # example: "AdminApp.Web-v2.5.1"
          # output: "AdminApp.Web"
          $packageName = ($release -split "-v")[0]

          switch ($packageName) {
            "AdminApp.Web": {
              $packages = @(
                  "EdFi.Suite3.ODS.AdminApp.Database",
                  "EdFi.Suite3.ODS.AdminApp.Web"
              )
            }
            "Admin.Api": {
              $packages = @( "EdFi.Suite3.ODS.Admin.Api" )
            }
            "AdminApp.Installer": {
              $packages = @( "EdFi.Suite3.Installer.AdminApp" )
            }
          }

          $arguments = @{
            FeedsURL    = "${{ env.ARTIFACTS_FEED_URL }}"
            PackagesURL = "${{ env.ARTIFACTS_PACKAGES_URL }}"
            Username    = "${{ env.ARTIFACTS_USERNAME }}"
            View        = "release"
            Packages    = $packages
            Password    = (ConvertTo-SecureString -String "${{ env.ARTIFACTS_API_KEY }}" -AsPlainText -Force)
          }

          .\eng\promote-packages.ps1 @arguments
